<?php

namespace AppBundle\Repository;

/**
 * WiadomoscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WiadomoscRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForList($filter)
    {
        $qb = $this
            ->createQueryBuilder('wiadomosc')
            ->select('wiadomosc')
            ->addOrderBy('wiadomosc.wyslano', 'DESC')
        ;

        if ('only_processed' === $filter) {
            $qb->andWhere('wiadomosc.dostarczono IS NOT NULL');
        }
        if ('only_not_processed' === $filter) {
            $qb->andWhere('contact.dostarczono IS NULL');
        }

        return $qb->getQuery()->getResult();
    }
}
